# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'epics_config.ui'
#
# Created: Thu Jul 24 12:11:18 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(461, 410)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.omega_pv_txt = QtGui.QLineEdit(self.groupBox)
        self.omega_pv_txt.setObjectName(_fromUtf8("omega_pv_txt"))
        self.gridLayout_2.addWidget(self.omega_pv_txt, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.x_pv_txt = QtGui.QLineEdit(self.groupBox)
        self.x_pv_txt.setObjectName(_fromUtf8("x_pv_txt"))
        self.gridLayout_2.addWidget(self.x_pv_txt, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.y_pv_txt = QtGui.QLineEdit(self.groupBox)
        self.y_pv_txt.setObjectName(_fromUtf8("y_pv_txt"))
        self.gridLayout_2.addWidget(self.y_pv_txt, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.z_pv_txt = QtGui.QLineEdit(self.groupBox)
        self.z_pv_txt.setObjectName(_fromUtf8("z_pv_txt"))
        self.gridLayout_2.addWidget(self.z_pv_txt, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.detector_pv_txt = QtGui.QLineEdit(self.groupBox)
        self.detector_pv_txt.setObjectName(_fromUtf8("detector_pv_txt"))
        self.gridLayout_2.addWidget(self.detector_pv_txt, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.user_shutter_rb = QtGui.QRadioButton(self.groupBox)
        self.user_shutter_rb.setChecked(True)
        self.user_shutter_rb.setObjectName(_fromUtf8("user_shutter_rb"))
        self.verticalLayout.addWidget(self.user_shutter_rb)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.shutter_pv_txt = QtGui.QLineEdit(self.groupBox)
        self.shutter_pv_txt.setObjectName(_fromUtf8("shutter_pv_txt"))
        self.gridLayout.addWidget(self.shutter_pv_txt, 0, 1, 1, 1)
        self.shutter_open_txt = QtGui.QLabel(self.groupBox)
        self.shutter_open_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shutter_open_txt.setObjectName(_fromUtf8("shutter_open_txt"))
        self.gridLayout.addWidget(self.shutter_open_txt, 1, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.shutter_close_pv = QtGui.QLabel(self.groupBox)
        self.shutter_close_pv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shutter_close_pv.setObjectName(_fromUtf8("shutter_close_pv"))
        self.gridLayout.addWidget(self.shutter_close_pv, 2, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.use_trajectory_rb = QtGui.QRadioButton(self.groupBox)
        self.use_trajectory_rb.setObjectName(_fromUtf8("use_trajectory_rb"))
        self.verticalLayout.addWidget(self.use_trajectory_rb)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.add_condtiion_btn = QtGui.QPushButton(Form)
        self.add_condtiion_btn.setObjectName(_fromUtf8("add_condtiion_btn"))
        self.horizontalLayout.addWidget(self.add_condtiion_btn)
        self.delete_condition_btn = QtGui.QPushButton(Form)
        self.delete_condition_btn.setObjectName(_fromUtf8("delete_condition_btn"))
        self.horizontalLayout.addWidget(self.delete_condition_btn)
        self.clear_condition_btn = QtGui.QPushButton(Form)
        self.clear_condition_btn.setObjectName(_fromUtf8("clear_condition_btn"))
        self.horizontalLayout.addWidget(self.clear_condition_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.conitions_table = QtGui.QTableWidget(Form)
        self.conitions_table.setObjectName(_fromUtf8("conitions_table"))
        self.conitions_table.setColumnCount(3)
        self.conitions_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.conitions_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.conitions_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.conitions_table.setHorizontalHeaderItem(2, item)
        self.conitions_table.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout_2.addWidget(self.conitions_table)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox.setTitle(_translate("Form", "Pv Names", None))
        self.label.setText(_translate("Form", "Omega:", None))
        self.label_2.setText(_translate("Form", "X:", None))
        self.label_3.setText(_translate("Form", "Y:", None))
        self.label_4.setText(_translate("Form", "Z:", None))
        self.label_5.setText(_translate("Form", "Detector:", None))
        self.user_shutter_rb.setText(_translate("Form", "Use Shutter", None))
        self.label_6.setText(_translate("Form", "Shutter:", None))
        self.shutter_open_txt.setText(_translate("Form", "Open:", None))
        self.shutter_close_pv.setText(_translate("Form", "Close:", None))
        self.use_trajectory_rb.setText(_translate("Form", "Use Trajectory scan", None))
        self.label_10.setText(_translate("Form", "Conditions", None))
        self.add_condtiion_btn.setText(_translate("Form", "Add", None))
        self.delete_condition_btn.setText(_translate("Form", "Delete", None))
        self.clear_condition_btn.setText(_translate("Form", "Clear", None))
        item = self.conitions_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "PV name", None))
        item = self.conitions_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Alias", None))
        item = self.conitions_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Value", None))

