# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\PP\SXRD_Collect\sxrd_collect\views\UiFiles\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets
from .utils import HoverButton

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_SXRDCollectWidget(object):
    def setupUi(self, SXRDCollectWidget):
        SXRDCollectWidget.setObjectName(_fromUtf8("SXRDCollectWidget"))
        SXRDCollectWidget.resize(919, 906)
        SXRDCollectWidget.setStyleSheet(_fromUtf8("#experiment_lbl, #sample_lbl, #standards_lbl {\n"
                                                  "    font: italic 20px;\n"
                                                  "}\n"
                                                  "\n"
                                                  "#title_lbl {\n"
                                                  "    font: bold 25px;\n"
                                                  "}"))
        self.verticalLayout = QtWidgets.QVBoxLayout(SXRDCollectWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.title_lbl = QtWidgets.QLabel(SXRDCollectWidget)
        self.title_lbl.setObjectName(_fromUtf8("title_lbl"))
        self.horizontalLayout_9.addWidget(self.title_lbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        myfont = QtGui.QFont()
        myfont.setPointSize(28)

        self.crysalis_config_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.crysalis_config_btn.setMinimumSize(QtCore.QSize(120, 35))
        self.crysalis_config_btn.setObjectName(_fromUtf8("crysalis_config_btn"))
        self.horizontalLayout_9.addWidget(self.crysalis_config_btn)
        self.crysalis_config_btn.setVisible(False)

        self.epics_config_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.epics_config_btn.setMinimumSize(QtCore.QSize(160, 60))
        self.epics_config_btn.setObjectName(_fromUtf8("epics_config_btn"))
        self.epics_config_btn.setVisible(False)
        self.horizontalLayout_9.addWidget(self.epics_config_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.line_8 = QtWidgets.QFrame(SXRDCollectWidget)
        self.line_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_8.setLineWidth(1)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout.addWidget(self.line_8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.experiment_lbl = QtWidgets.QLabel(SXRDCollectWidget)
        self.experiment_lbl.setObjectName(_fromUtf8("experiment_lbl"))
        self.horizontalLayout_8.addWidget(self.experiment_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.load_setup_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.load_setup_btn.setObjectName(_fromUtf8("load_setup_btn"))
        self.horizontalLayout_8.addWidget(self.load_setup_btn)
        self.save_setup_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.save_setup_btn.setObjectName(_fromUtf8("save_setup_btn"))
        self.horizontalLayout_8.addWidget(self.save_setup_btn)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.add_setup_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.add_setup_btn.setObjectName(_fromUtf8("add_setup_btn"))
        self.horizontalLayout_6.addWidget(self.add_setup_btn)
        self.delete_setup_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.delete_setup_btn.setObjectName(_fromUtf8("delete_setup_btn"))
        self.horizontalLayout_6.addWidget(self.delete_setup_btn)
        self.clear_setup_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.clear_setup_btn.setObjectName(_fromUtf8("clear_setup_btn"))
        self.horizontalLayout_6.addWidget(self.clear_setup_btn)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.line_7 = QtWidgets.QFrame(SXRDCollectWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout.addWidget(self.line_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.widget = QtWidgets.QWidget(SXRDCollectWidget)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.filepath_txt = QtWidgets.QLineEdit(self.widget)
        self.filepath_txt.setObjectName(_fromUtf8("filepath_txt"))
        self.gridLayout.addWidget(self.filepath_txt, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.filename_txt = QtWidgets.QLineEdit(self.widget)
        self.filename_txt.setObjectName(_fromUtf8("filename_txt"))
        self.gridLayout.addWidget(self.filename_txt, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.point_txt = QtWidgets.QLineEdit(self.widget)
        self.point_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.point_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.point_txt.setObjectName(_fromUtf8("point_txt"))
        self.horizontalLayout_10.addWidget(self.point_txt)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.get_folder_btn = QtWidgets.QPushButton(self.widget)
        self.get_folder_btn.setMaximumSize(QtCore.QSize(45, 16777215))
        self.get_folder_btn.setObjectName(_fromUtf8("get_folder_btn"))
        self.gridLayout.addWidget(self.get_folder_btn, 1, 3, 1, 1)
        self.select_folder_btn = QtWidgets.QPushButton(self.widget)
        self.select_folder_btn.setMaximumSize(QtCore.QSize(45, 16777215))
        self.select_folder_btn.setObjectName(_fromUtf8("select_folder_btn"))
        self.gridLayout.addWidget(self.select_folder_btn, 1, 4, 1, 1)
        self.get_basename_btn = QtWidgets.QPushButton(self.widget)
        self.get_basename_btn.setMaximumSize(QtCore.QSize(45, 16777215))
        self.get_basename_btn.setObjectName(_fromUtf8("get_basename_btn"))
        self.gridLayout.addWidget(self.get_basename_btn, 0, 3, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.frame_number_txt = QtWidgets.QLineEdit(self.widget)
        self.frame_number_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_number_txt.setObjectName(_fromUtf8("frame_number_txt"))
        self.horizontalLayout_14.addWidget(self.frame_number_txt)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.framenr_reset_btn = QtWidgets.QPushButton(self.widget)
        self.framenr_reset_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.framenr_reset_btn.setObjectName(_fromUtf8("framenr_reset_btn"))
        self.horizontalLayout_14.addWidget(self.framenr_reset_btn)
        self.gridLayout.addLayout(self.horizontalLayout_14, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.get_framenr_btn = QtWidgets.QPushButton(self.widget)
        self.get_framenr_btn.setMaximumSize(QtCore.QSize(45, 16777215))
        self.get_framenr_btn.setObjectName(_fromUtf8("get_framenr_btn"))
        self.gridLayout.addWidget(self.get_framenr_btn, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.open_path_btn = QtWidgets.QPushButton(self.widget)
        self.open_path_btn.setMaximumSize(QtCore.QSize(10, 10))
        self.open_path_btn.setText(_fromUtf8(""))
        self.open_path_btn.setObjectName(_fromUtf8("open_path_btn"))
        self.horizontalLayout_4.addWidget(self.open_path_btn)
        self.example_filename_lbl = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.example_filename_lbl.sizePolicy().hasHeightForWidth())
        self.example_filename_lbl.setSizePolicy(sizePolicy)
        self.example_filename_lbl.setMinimumSize(QtCore.QSize(0, 22))
        self.example_filename_lbl.setMaximumSize(QtCore.QSize(16777215, 25))
        self.example_filename_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.example_filename_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.example_filename_lbl.setScaledContents(False)
        self.example_filename_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.example_filename_lbl.setWordWrap(False)
        self.example_filename_lbl.setObjectName(_fromUtf8("example_filename_lbl"))
        self.horizontalLayout_4.addWidget(self.example_filename_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.rename_files_cb = QtWidgets.QCheckBox(self.widget)
        self.rename_files_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rename_files_cb.setChecked(True)
        self.rename_files_cb.setObjectName(_fromUtf8("rename_files_cb"))
        self.verticalLayout_2.addWidget(self.rename_files_cb)

        self.renames_files_hlayout = QtWidgets.QHBoxLayout()
        self.rename_files_sp_cb = QtWidgets.QCheckBox(self.widget)
        self.rename_files_sp_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rename_files_sp_cb.setChecked(True)
        self.rename_files_sp_cb.setObjectName(_fromUtf8("rename_files_sp_cb"))
        self.renames_files_hlayout.addWidget(self.rename_files_sp_cb)

        self.rename_files_pp_cb = QtWidgets.QCheckBox(self.widget)
        self.rename_files_pp_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rename_files_pp_cb.setChecked(True)
        self.rename_files_pp_cb.setObjectName(_fromUtf8("rename_files_pp_cb"))
        self.renames_files_hlayout.addWidget(self.rename_files_pp_cb)

        self.rename_files_en_cb = QtWidgets.QCheckBox(self.widget)
        self.rename_files_en_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rename_files_en_cb.setChecked(True)
        self.rename_files_en_cb.setObjectName(_fromUtf8("rename_files_en_cb"))
        self.renames_files_hlayout.addWidget(self.rename_files_en_cb)

        self.rename_files_suf_cb = QtWidgets.QCheckBox(self.widget)
        self.rename_files_suf_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rename_files_suf_cb.setChecked(True)
        self.rename_files_suf_cb.setObjectName(_fromUtf8("rename_files_suf_cb"))
        self.renames_files_hlayout.addWidget(self.rename_files_suf_cb)

        # self.rename_files_fn_cb = QtWidgets.QCheckBox(self.widget)
        # self.rename_files_fn_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.rename_files_fn_cb.setChecked(True)
        # self.rename_files_fn_cb.setObjectName(_fromUtf8("rename_files_fn_cb"))
        # self.renames_files_hlayout.addWidget(self.rename_files_fn_cb)

        self.verticalLayout_2.addLayout(self.renames_files_hlayout)

        self.rename_after_cb = QtWidgets.QCheckBox(self.widget)
        self.rename_after_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rename_after_cb.setChecked(True)
        self.rename_after_cb.setObjectName(_fromUtf8("rename_after_cb"))
        self.verticalLayout_2.addWidget(self.rename_after_cb)
        self.reset_sample_position_cb = QtWidgets.QCheckBox(self.widget)
        self.reset_sample_position_cb.setChecked(True)
        self.reset_sample_position_cb.setObjectName(_fromUtf8("reset_sample_position_cb"))
        self.verticalLayout_2.addWidget(self.reset_sample_position_cb)
        self.reset_detector_position_cb = QtWidgets.QCheckBox(self.widget)
        self.reset_detector_position_cb.setChecked(True)
        self.reset_detector_position_cb.setObjectName(_fromUtf8("reset_detector_position_cb"))
        self.verticalLayout_2.addWidget(self.reset_detector_position_cb)
        self.no_suffices_cb = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.no_suffices_cb.sizePolicy().hasHeightForWidth())
        self.no_suffices_cb.setSizePolicy(sizePolicy)
        self.no_suffices_cb.setObjectName(_fromUtf8("no_suffices_cb"))
        self.verticalLayout_2.addWidget(self.no_suffices_cb)
        self.horizontalLayout_5.addWidget(self.widget)
        self.setup_table = QtWidgets.QTableWidget(SXRDCollectWidget)
        self.setup_table.setMinimumSize(QtCore.QSize(500, 0))
        self.setup_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.setup_table.setToolTip(_fromUtf8(""))
        self.setup_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.setup_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.setup_table.setWordWrap(True)
        self.setup_table.setObjectName(_fromUtf8("setup_table"))
        self.setup_table.setColumnCount(8)  # was 9 for steps/image column
        self.setup_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.setup_table.setHorizontalHeaderItem(7, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setup_table.setHorizontalHeaderItem(8, item)
        self.setup_table.horizontalHeader().setVisible(True)
        self.setup_table.horizontalHeader().setCascadingSectionResizes(False)
        self.setup_table.horizontalHeader().setDefaultSectionSize(62)
        self.setup_table.horizontalHeader().setHighlightSections(True)
        self.setup_table.horizontalHeader().setMinimumSectionSize(34)
        self.setup_table.verticalHeader().setVisible(False)
        self.horizontalLayout_5.addWidget(self.setup_table)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.omega_pm1_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.omega_pm1_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.omega_pm1_btn.setObjectName(_fromUtf8("omega_pm1_btn"))
        self.verticalLayout_5.addWidget(self.omega_pm1_btn)
        self.omega_pm3_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.omega_pm3_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.omega_pm3_btn.setObjectName(_fromUtf8("omega_pm3_btn"))
        self.verticalLayout_5.addWidget(self.omega_pm3_btn)
        self.omega_pm10_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.omega_pm10_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.omega_pm10_btn.setObjectName(_fromUtf8("omega_pm10_btn"))
        self.verticalLayout_5.addWidget(self.omega_pm10_btn)
        self.omega_pm20_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.omega_pm20_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.omega_pm20_btn.setObjectName(_fromUtf8("omega_pm20_btn"))
        self.verticalLayout_5.addWidget(self.omega_pm20_btn)
        self.omega_pm38_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.omega_pm38_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.omega_pm38_btn.setObjectName(_fromUtf8("omega_pm38_btn"))
        self.verticalLayout_5.addWidget(self.omega_pm38_btn)
        spacerItem4 = QtWidgets.QSpacerItem(25, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtWidgets.QLabel(SXRDCollectWidget)
        self.label_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.omega_range_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.omega_range_txt.sizePolicy().hasHeightForWidth())
        self.omega_range_txt.setSizePolicy(sizePolicy)
        self.omega_range_txt.setMaximumSize(QtCore.QSize(30, 16777215))
        self.omega_range_txt.setObjectName(_fromUtf8("omega_range_txt"))
        self.horizontalLayout_12.addWidget(self.omega_range_txt)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.omega_set_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.omega_set_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.omega_set_btn.setObjectName(_fromUtf8("omega_set_btn"))
        self.verticalLayout_5.addWidget(self.omega_set_btn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(SXRDCollectWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sample_lbl = QtWidgets.QLabel(SXRDCollectWidget)
        self.detector_lbl = QtWidgets.QLabel(SXRDCollectWidget)
        self.sample_lbl.setObjectName(_fromUtf8("sample_lbl"))
        self.horizontalLayout_3.addWidget(self.sample_lbl)
        self.current_position_lbl = QtWidgets.QLabel(SXRDCollectWidget)
        self.current_position_lbl.setObjectName(_fromUtf8("current_position_lbl"))
        self.horizontalLayout_3.addWidget(self.current_position_lbl)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.add_sample_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.add_sample_btn.setObjectName(_fromUtf8("add_sample_btn"))
        self.horizontalLayout.addWidget(self.add_sample_btn)
        self.delete_sample_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.delete_sample_btn.setObjectName(_fromUtf8("delete_sample_btn"))
        self.horizontalLayout.addWidget(self.delete_sample_btn)
        self.clear_sample_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.clear_sample_btn.setObjectName(_fromUtf8("clear_sample_btn"))
        self.horizontalLayout.addWidget(self.clear_sample_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_5 = QtWidgets.QFrame(SXRDCollectWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sample_points_table = QtWidgets.QTableWidget(SXRDCollectWidget)
        self.sample_points_table.setStyleSheet(_fromUtf8("QPushButton {\n"
                                                         "    height: 18px;\n"
                                                         "    border: 1px solid #000;\n"
                                                         "    border-radius:2px;\n"
                                                         "    padding-left: 8px;\n"
                                                         "    padding-right: 8px;\n"
                                                         "    margin: 5px;\n"
                                                         "}\n"
                                                         "\n"
                                                         "QPushButton::pressed{\n"
                                                         "    margin-left: 7px;\n"
                                                         "    margin-top: 7px;\n"
                                                         "}\n"
                                                         "QPushButton::hover{\n"
                                                         "    background-color: #EEE\n"
                                                         "}"))
        self.sample_points_table.setLineWidth(0)
        self.sample_points_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sample_points_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sample_points_table.setColumnCount(6)
        self.sample_points_table.setObjectName(_fromUtf8("sample_points_table"))
        self.sample_points_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sample_points_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sample_points_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sample_points_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sample_points_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sample_points_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sample_points_table.setHorizontalHeaderItem(5, item)
        self.sample_points_table.horizontalHeader().setVisible(True)
        self.sample_points_table.horizontalHeader().setDefaultSectionSize(80)
        self.sample_points_table.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.sample_points_table)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_10 = QtWidgets.QLabel(SXRDCollectWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_8.addWidget(self.label_10)
        self.check_all_still_cb = QtWidgets.QCheckBox(SXRDCollectWidget)
        self.check_all_still_cb.setObjectName(_fromUtf8("check_all_still_cb"))
        self.verticalLayout_8.addWidget(self.check_all_still_cb)
        self.check_all_wide_cb = QtWidgets.QCheckBox(SXRDCollectWidget)
        self.check_all_wide_cb.setObjectName(_fromUtf8("check_all_wide_cb"))
        self.verticalLayout_8.addWidget(self.check_all_wide_cb)
        self.check_all_step_cb = QtWidgets.QCheckBox(SXRDCollectWidget)
        self.check_all_step_cb.setObjectName(_fromUtf8("check_all_step_cb"))
        self.verticalLayout_8.addWidget(self.check_all_step_cb)

        spacerItem6 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)

        self.total_frames_txt = QtWidgets.QLabel(SXRDCollectWidget)
        self.total_frames_txt.setText(_fromUtf8(""))
        self.total_frames_txt.setObjectName(_fromUtf8("total_frames_txt"))
        self.verticalLayout_8.addWidget(self.total_frames_txt)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(SXRDCollectWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_11.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtWidgets.QLabel(SXRDCollectWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(SXRDCollectWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.x_max_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_max_txt.sizePolicy().hasHeightForWidth())
        self.x_max_txt.setSizePolicy(sizePolicy)
        self.x_max_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_max_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_max_txt.setObjectName(_fromUtf8("x_max_txt"))
        self.gridLayout_2.addWidget(self.x_max_txt, 1, 2, 1, 1)
        self.y_step_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_step_txt.sizePolicy().hasHeightForWidth())
        self.y_step_txt.setSizePolicy(sizePolicy)
        self.y_step_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_step_txt.setObjectName(_fromUtf8("y_step_txt"))
        self.gridLayout_2.addWidget(self.y_step_txt, 2, 3, 1, 1)
        self.y_min_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_min_txt.sizePolicy().hasHeightForWidth())
        self.y_min_txt.setSizePolicy(sizePolicy)
        self.y_min_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_min_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_min_txt.setObjectName(_fromUtf8("y_min_txt"))
        self.gridLayout_2.addWidget(self.y_min_txt, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.x_step_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_step_txt.sizePolicy().hasHeightForWidth())
        self.x_step_txt.setSizePolicy(sizePolicy)
        self.x_step_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_step_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_step_txt.setObjectName(_fromUtf8("x_step_txt"))
        self.gridLayout_2.addWidget(self.x_step_txt, 1, 3, 1, 1)
        self.x_min_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_min_txt.sizePolicy().hasHeightForWidth())
        self.x_min_txt.setSizePolicy(sizePolicy)
        self.x_min_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_min_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_min_txt.setObjectName(_fromUtf8("x_min_txt"))
        self.gridLayout_2.addWidget(self.x_min_txt, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.y_max_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_max_txt.sizePolicy().hasHeightForWidth())
        self.y_max_txt.setSizePolicy(sizePolicy)
        self.y_max_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.y_max_txt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_max_txt.setObjectName(_fromUtf8("y_max_txt"))
        self.gridLayout_2.addWidget(self.y_max_txt, 2, 2, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_2)
        self.create_map_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_map_btn.sizePolicy().hasHeightForWidth())
        self.create_map_btn.setSizePolicy(sizePolicy)
        self.create_map_btn.setObjectName(_fromUtf8("create_map_btn"))
        self.horizontalLayout_11.addWidget(self.create_map_btn)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.set_map_range_01_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_range_01_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_range_01_btn.setObjectName(_fromUtf8("set_map_range_01_btn"))
        self.gridLayout_3.addWidget(self.set_map_range_01_btn, 2, 0, 1, 1)
        self.set_map_step_002_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_step_002_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_step_002_btn.setObjectName(_fromUtf8("set_map_step_002_btn"))
        self.gridLayout_3.addWidget(self.set_map_step_002_btn, 1, 4, 1, 1)
        self.set_map_range_006_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_range_006_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_range_006_btn.setObjectName(_fromUtf8("set_map_range_006_btn"))
        self.gridLayout_3.addWidget(self.set_map_range_006_btn, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(SXRDCollectWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 3, 1, 1)
        self.set_map_step_005_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_step_005_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_step_005_btn.setObjectName(_fromUtf8("set_map_step_005_btn"))
        self.gridLayout_3.addWidget(self.set_map_step_005_btn, 1, 3, 1, 1)
        self.set_map_step_003_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_step_003_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_step_003_btn.setObjectName(_fromUtf8("set_map_step_003_btn"))
        self.gridLayout_3.addWidget(self.set_map_step_003_btn, 2, 3, 1, 1)
        self.set_map_range_02_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_range_02_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_range_02_btn.setObjectName(_fromUtf8("set_map_range_02_btn"))
        self.gridLayout_3.addWidget(self.set_map_range_02_btn, 1, 0, 1, 1)
        self.set_map_range_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_range_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_range_btn.setObjectName(_fromUtf8("set_map_range_btn"))
        self.gridLayout_3.addWidget(self.set_map_range_btn, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(SXRDCollectWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.map_range_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        self.map_range_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.map_range_txt.setObjectName(_fromUtf8("map_range_txt"))
        self.gridLayout_3.addWidget(self.map_range_txt, 3, 0, 1, 1)
        self.set_map_step_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_step_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_step_btn.setObjectName(_fromUtf8("set_map_step_btn"))
        self.gridLayout_3.addWidget(self.set_map_step_btn, 3, 4, 1, 1)
        self.set_map_range_004_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_range_004_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_range_004_btn.setObjectName(_fromUtf8("set_map_range_004_btn"))
        self.gridLayout_3.addWidget(self.set_map_range_004_btn, 2, 1, 1, 1)
        self.set_map_step_001_btn = QtWidgets.QPushButton(SXRDCollectWidget)
        self.set_map_step_001_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.set_map_step_001_btn.setObjectName(_fromUtf8("set_map_step_001_btn"))
        self.gridLayout_3.addWidget(self.set_map_step_001_btn, 2, 4, 1, 1)
        self.map_step_txt = QtWidgets.QLineEdit(SXRDCollectWidget)
        self.map_step_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.map_step_txt.setObjectName(_fromUtf8("map_step_txt"))
        self.gridLayout_3.addWidget(self.map_step_txt, 3, 3, 1, 1)
        self.line_6 = QtWidgets.QFrame(SXRDCollectWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 0, 2, 4, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        # Added reset button
        self.btn_reset = QtWidgets.QPushButton(SXRDCollectWidget)
        self.btn_reset.setSizePolicy(sizePolicy)

        # Added power cycle detector button. Chris
        self.btn_power_cycle = QtWidgets.QPushButton(SXRDCollectWidget)
        self.lbl_iterations = QtWidgets.QLabel(SXRDCollectWidget)
        self.lbl_iterations.setText("#")
        self.io_iterations = QtWidgets.QLineEdit(SXRDCollectWidget)
        self.io_iterations.setText("1")
        self.io_iterations.setMaximumWidth(60)
        self.io_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_power_cycle.setSizePolicy(sizePolicy)
        layout_power_cycle_top = QtWidgets.QVBoxLayout()
        layout_power_cycle_top.addWidget(self.btn_power_cycle)
        layout_power_cycle_bottom = QtWidgets.QHBoxLayout()
        layout_power_cycle_bottom.addWidget(self.lbl_iterations, alignment=QtCore.Qt.AlignLeft)
        layout_power_cycle_bottom.addWidget(self.io_iterations, alignment=QtCore.Qt.AlignLeft)
        layout_vert3_split = QtWidgets.QHBoxLayout()
        layout_vert3_split.addLayout(layout_power_cycle_top)
        layout_vert3_split.addWidget(self.btn_reset)

        self.verticalLayout_3.addLayout(layout_vert3_split)

        layout_vert3_bottom = QtWidgets.QHBoxLayout()
        layout_vert3_bottom.addLayout(layout_power_cycle_bottom)
        layout_vert3_bottom.addStretch(1)
        self.verticalLayout_3.addLayout(layout_vert3_bottom)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.line_3 = QtWidgets.QFrame(SXRDCollectWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.status_txt = QtWidgets.QTextEdit(SXRDCollectWidget)
        self.status_txt.setMinimumSize(QtCore.QSize(0, 75))
        self.status_txt.setObjectName(_fromUtf8("status_txt"))
        self.horizontalLayout_7.addWidget(self.status_txt)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.status_lbl = QtWidgets.QLabel(SXRDCollectWidget)
        self.status_lbl.setText(_fromUtf8(""))
        self.status_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.status_lbl.setObjectName(_fromUtf8("status_lbl"))
        self.verticalLayout_4.addWidget(self.status_lbl)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.override_pilatus_limits_cb = QtWidgets.QCheckBox(SXRDCollectWidget)
        self.override_pilatus_limits_cb.setObjectName(_fromUtf8("override_pilatus_limits_cb"))
        self.override_pilatus_limits_cb.setChecked(False)
        self.verticalLayout_4.addWidget(self.override_pilatus_limits_cb)
        self.override_pilatus_limits_cb.setVisible(False)

        self.repeat_cb = QtWidgets.QCheckBox(SXRDCollectWidget)
        self.repeat_cb.setObjectName(_fromUtf8("repeat_cb"))
        self.repeat_cb.setChecked(False)
        self.verticalLayout_4.addWidget(self.repeat_cb)

        self.test_mode_cb = QtWidgets.QCheckBox(SXRDCollectWidget)
        self.test_mode_cb.setObjectName(_fromUtf8("test_mode_cb"))
        self.test_mode_cb.setChecked(False)
        self.verticalLayout_4.addWidget(self.test_mode_cb)

        self.collect_btn =HoverButton(SXRDCollectWidget)
        self.collect_btn.setMinimumSize(QtCore.QSize(130, 70))
        self.collect_btn.setObjectName(_fromUtf8("collect_btn"))
        self.verticalLayout_4.addWidget(self.collect_btn)

        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)


        self.retranslateUi(SXRDCollectWidget)
        QtCore.QMetaObject.connectSlotsByName(SXRDCollectWidget)

    def retranslateUi(self, SXRDCollectWidget):
        SXRDCollectWidget.setWindowTitle(_translate("SXRDCollectWidget", "Form", None))
        self.title_lbl.setText(_translate("SXRDCollectWidget", "Single Crystal X-ray Diffraction", None))
        self.crysalis_config_btn.setText(_translate("SXRDCollectWidget", "Crysalis \n Configuration", None))
        self.epics_config_btn.setText(_translate("SXRDCollectWidget", "EPICS \n Configuration", None))
        self.experiment_lbl.setText(_translate("SXRDCollectWidget", "Experiment Setup", None))
        self.load_setup_btn.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p>Load experiment setup(s) from *.ini file</p></body></html>", None))
        self.load_setup_btn.setText(_translate("SXRDCollectWidget", "Load", None))
        self.save_setup_btn.setToolTip(_translate("SXRDCollectWidget", "Save current experiment setup(s) to *.ini file", None))
        self.save_setup_btn.setText(_translate("SXRDCollectWidget", "Save", None))
        self.add_setup_btn.setText(_translate("SXRDCollectWidget", "Add", None))
        self.delete_setup_btn.setText(_translate("SXRDCollectWidget", "Delete", None))
        self.clear_setup_btn.setText(_translate("SXRDCollectWidget", "Clear", None))
        self.label_3.setText(_translate("SXRDCollectWidget", "Basename:", None))
        self.point_txt.setText(_translate("SXRDCollectWidget", "1", None))
        self.label.setText(_translate("SXRDCollectWidget", "Point:", None))
        self.label_4.setText(_translate("SXRDCollectWidget", "Folder:", None))
        self.get_folder_btn.setToolTip(_translate("SXRDCollectWidget", "Will get current epics filepath", None))
        self.get_folder_btn.setText(_translate("SXRDCollectWidget", "Update", None))

        self.select_folder_btn.setText(_translate("SXRDCollectWidget", "Select", None))

        self.get_basename_btn.setToolTip(_translate("SXRDCollectWidget", "Will get current basename from epics", None))
        self.get_basename_btn.setText(_translate("SXRDCollectWidget", "Update", None))
        self.frame_number_txt.setText(_translate("SXRDCollectWidget", "1", None))
        self.frame_number_txt.setPlaceholderText(_translate("SXRDCollectWidget", "Number", None))
        self.framenr_reset_btn.setText(_translate("SXRDCollectWidget", "Reset", None))
        self.label_9.setText(_translate("SXRDCollectWidget", "Frame Nr.", None))
        self.get_framenr_btn.setToolTip(_translate("SXRDCollectWidget", "Will get current Frame Nr from epics", None))
        self.get_framenr_btn.setText(_translate("SXRDCollectWidget", "Update", None))
        self.example_filename_lbl.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p><span style=\" font-weight:600; color:#888888;\">Grey</span>: Example Filename</p><p><span style=\" font-weight:600; color:#aa0000;\">Red</span>: The file with the same name exists and will be overwritten</p><p><span style=\" font-weight:600; color:#ff5500;\">Orange</span>: Path does not exist</p><p><span style=\" font-weight:600; color:#228b22;\">Green</span>: Everything Ok (at least the first file will not be overwritten)</p></body></html>", None))
        self.example_filename_lbl.setText(_translate("SXRDCollectWidget", "<html><head/><body><p align=\"right\">example_lbl</p></body></html>", None))
        self.rename_files_cb.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p>Will name files in the following way:</p><p><span style=\" color:#0000ff;\">basename_S1_P1_E1_s_FrameNr</span></p><p>S1 - sample name</p><p>P1 - point number</p><p>E1 - experimental setup name</p><p>s - step scan (w - for wide scan, empty for still image)</p><p>FrameNr - Frame number (will always start with 001)</p></body></html>", None))
        self.rename_files_cb.setText(_translate("SXRDCollectWidget", "Rename Files", None))
        self.rename_files_sp_cb.setToolTip(_translate("SXRDCollectWidget", "Adds the name from the sample point table", None))
        self.rename_files_sp_cb.setText('S1')
        self.rename_files_pp_cb.setToolTip(
            _translate("SXRDCollectWidget", "Adds the number from the 'Point' field above", None))
        self.rename_files_pp_cb.setText('P1')
        self.rename_files_en_cb.setToolTip(
            _translate("SXRDCollectWidget", "Adds the Experiment name from the experiment setup table", None))
        self.rename_files_en_cb.setText('E1')
        self.rename_files_suf_cb.setToolTip(
            _translate("SXRDCollectWidget", "Adds suffix _w for wide, and _s for step", None))
        self.rename_files_suf_cb.setText('Suffix')
        # self.rename_files_fn_cb.setToolTip(
        #     _translate("SXRDCollectWidget", "Adds frame number (and advances it)", None))
        # self.rename_files_fn_cb.setText('Frame #')
        self.rename_after_cb.setText(_translate("SXRDCollectWidget", "Reset name after Measurement", None))
        self.reset_sample_position_cb.setText(_translate("SXRDCollectWidget", "Reset Sample Position", None))
        self.reset_detector_position_cb.setText(_translate("SXRDCollectWidget", "Reset Detector Position", None))
        self.no_suffices_cb.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p><span style=\" color:#000000;\">If this option is checked, the filename will be: </span><span style=\" color:#0000ff;\">Basename_Frame Nr</span></p><p><span style=\" color:#ff0000;\">In case of several experimental setups/sample points, the Frame Nr will continuously increase wihtout any changes in the basename!</span></p></body></html>", None))
        self.no_suffices_cb.setText(_translate("SXRDCollectWidget", "Do not add suffixes to basename", None))
        item = self.setup_table.horizontalHeaderItem(0)
        item.setText(_translate("SXRDCollectWidget", "Name", None))
        item = self.setup_table.horizontalHeaderItem(1)
        item.setText(_translate("SXRDCollectWidget", "Det X", None))
        item = self.setup_table.horizontalHeaderItem(2)
        item.setText(_translate("SXRDCollectWidget", "Det Z", None))
        item = self.setup_table.horizontalHeaderItem(3)
        item.setText(_translate("SXRDCollectWidget", "ω Start", None))
        item = self.setup_table.horizontalHeaderItem(4)
        item.setText(_translate("SXRDCollectWidget", "ω End", None))
        item = self.setup_table.horizontalHeaderItem(5)
        item.setText(_translate("SXRDCollectWidget", "ω Step", None))
        item = self.setup_table.horizontalHeaderItem(6)
        item.setText(_translate("SXRDCollectWidget", "Time/step", None))
        item = self.setup_table.horizontalHeaderItem(7)
        item.setText(_translate("SXRDCollectWidget", "Total time", None))
        # item = self.setup_table.horizontalHeaderItem(8)
        # item.setText(_translate("SXRDCollectWidget", "Steps/Image", None))
        self.omega_pm1_btn.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p>Set:</p><p>ω Start = -91.0</p><p>ω End   = -89.0</p></body></html>", None))
        self.omega_pm1_btn.setText(_translate("SXRDCollectWidget", "ω ± 1", None))
        self.omega_pm3_btn.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p>Set:</p><p>ω Start = -93.0</p><p>ω End   = -87.0</p></body></html>", None))
        self.omega_pm3_btn.setText(_translate("SXRDCollectWidget", "ω ± 3", None))
        self.omega_pm10_btn.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p>Set:</p><p>ω Start = -100.0</p><p>ω End   = -80.0</p></body></html>", None))
        self.omega_pm10_btn.setText(_translate("SXRDCollectWidget", "ω ± 10", None))
        self.omega_pm20_btn.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p>Set:</p><p>ω Start = -110.0</p><p>ω End   = -70.0</p></body></html>", None))
        self.omega_pm20_btn.setText(_translate("SXRDCollectWidget", "ω ± 20", None))
        self.omega_pm38_btn.setToolTip(_translate("SXRDCollectWidget", "<html><head/><body><p>Set:</p><p>ω Start = -128.0</p><p>ω End   = -52.0</p></body></html>", None))
        self.omega_pm38_btn.setText(_translate("SXRDCollectWidget", "ω ± 38", None))
        self.label_11.setText(_translate("SXRDCollectWidget", "ω ± ", None))
        self.omega_range_txt.setText(_translate("SXRDCollectWidget", "5", None))
        self.omega_set_btn.setText(_translate("SXRDCollectWidget", "Set", None))
        self.sample_lbl.setText(_translate("SXRDCollectWidget", "Sample Points", None))
        self.current_position_lbl.setText(_translate("SXRDCollectWidget", "   Current Position: ", None))
        self.add_sample_btn.setText(_translate("SXRDCollectWidget", "Add", None))
        self.delete_sample_btn.setText(_translate("SXRDCollectWidget", "Delete", None))
        self.clear_sample_btn.setText(_translate("SXRDCollectWidget", "Clear", None))
        item = self.sample_points_table.horizontalHeaderItem(0)
        item.setText(_translate("SXRDCollectWidget", "Point", None))
        item = self.sample_points_table.horizontalHeaderItem(1)
        item.setText(_translate("SXRDCollectWidget", "x", None))
        item = self.sample_points_table.horizontalHeaderItem(2)
        item.setText(_translate("SXRDCollectWidget", "y", None))
        item = self.sample_points_table.horizontalHeaderItem(3)
        item.setText(_translate("SXRDCollectWidget", "z", None))
        self.label_10.setText(_translate("SXRDCollectWidget", "Select all:", None))
        self.check_all_still_cb.setText(_translate("SXRDCollectWidget", "still", None))
        self.check_all_wide_cb.setText(_translate("SXRDCollectWidget", "wide", None))
        self.check_all_step_cb.setText(_translate("SXRDCollectWidget", "step", None))
        self.label_8.setText(_translate("SXRDCollectWidget", "y", None))
        self.label_2.setText(_translate("SXRDCollectWidget", "x", None))
        self.x_max_txt.setText(_translate("SXRDCollectWidget", "0.01", None))
        self.y_step_txt.setText(_translate("SXRDCollectWidget", "0.005", None))
        self.y_min_txt.setText(_translate("SXRDCollectWidget", "-0.01", None))
        self.label_5.setText(_translate("SXRDCollectWidget", "step", None))
        self.x_step_txt.setText(_translate("SXRDCollectWidget", "0.005", None))
        self.x_min_txt.setText(_translate("SXRDCollectWidget", "-0.01", None))
        self.label_6.setText(_translate("SXRDCollectWidget", "min", None))
        self.label_7.setText(_translate("SXRDCollectWidget", "max", None))
        self.y_max_txt.setText(_translate("SXRDCollectWidget", "0.01", None))
        self.create_map_btn.setText(_translate("SXRDCollectWidget", "Create Map", None))
        self.set_map_range_01_btn.setText(_translate("SXRDCollectWidget", "± 0.01", None))
        self.set_map_step_002_btn.setText(_translate("SXRDCollectWidget", "0.002", None))
        self.set_map_range_006_btn.setText(_translate("SXRDCollectWidget", "± 0.006", None))
        self.label_13.setText(_translate("SXRDCollectWidget", "Step:", None))
        self.set_map_step_005_btn.setText(_translate("SXRDCollectWidget", "0.005", None))
        self.set_map_step_003_btn.setText(_translate("SXRDCollectWidget", "0.003", None))
        self.set_map_range_02_btn.setText(_translate("SXRDCollectWidget", "± 0.02", None))
        self.set_map_range_btn.setText(_translate("SXRDCollectWidget", "Set", None))
        self.label_12.setText(_translate("SXRDCollectWidget", "Range:", None))
        self.map_range_txt.setText(_translate("SXRDCollectWidget", "0.005", None))
        self.set_map_step_btn.setText(_translate("SXRDCollectWidget", "Set", None))
        self.set_map_range_004_btn.setText(_translate("SXRDCollectWidget", "± 0.004", None))
        self.set_map_step_001_btn.setText(_translate("SXRDCollectWidget", "0.001", None))
        self.map_step_txt.setText(_translate("SXRDCollectWidget", "0.005", None))
        self.repeat_cb.setText(_translate("SXRDCollectWidget", "Repeat", None))
        self.test_mode_cb.setText(_translate("SXRDCollectWidget", "Test Mode", None))
        self.override_pilatus_limits_cb.setText(_translate("SXRDCollectWidget", "Force 0.1 deg steps", None))
        self.collect_btn.setText(_translate("SXRDCollectWidget", "Collect", None))
        self.btn_reset.setText(_translate("SXRDCollectWidget", "Reset\n(Pilatus Only)", None))
        self.btn_power_cycle.setText(_translate("SXRDCollectWidget", "Power Cycle\n(Pilatus Only)", None))
